sudo: required
language: rust

services:
  - docker

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

env:
  global:
    - RUST_BACKTRACE=1
  matrix:
    - TARGET_ARCH=x86_64
    - TARGET_ARCH=i686

matrix:
  exclude:
    - os: osx
      env: TARGET_ARCH=i686
  allow_failures:
    - rust: nightly

cache: cargo

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew install vapoursynth;
    else
      docker build -t testing-environment .travis/$TARGET_ARCH;
    fi

script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      sh .travis/script.sh;
    else
      docker run --mount type=bind,source=$PWD,target=/vapoursynth-rs
        -e TARGET_ARCH -e TRAVIS_RUST_VERSION -e RUST_BACKTRACE
        testing-environment /bin/sh vapoursynth-rs/.travis/script-docker.sh;
    fi

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TARGET_ARCH" = "x86_64" ]; then
      export DEPLOY=1;
    else
      export DEPLOY=0;
    fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: target/doc
  on:
    branch: master
    rust: stable
    condition: "$DEPLOY = 1"
